---
- name: "Install Calico CNI on EKS using Kubernetes Manifest File"
  hosts: localhost
  vars:
    aws_eks_cluster_name: "{{ aws_eks_cluster_name }}"
  tasks:
    - name: "Execute the script to configure aws credentials to run kube commands"
      shell: "sh set-temp-cred.sh"
    - name: "Update kube config file"
      command: "aws eks update-kubeconfig --name {{ aws_eks_cluster_name }} --region eu-central-1"
      register: eks_kube_config_update
    - name: "Show kube config update output"
      debug:
        msg: "{{ eks_kube_config_update.stdout }}"
    - name: "Delete the aws-node daemon set to disable AWS VPC networking for pods"
      command: kubectl delete daemonset -n kube-system aws-node
      register: delete_vpc_cni
      ignore_errors: yes
    - name: "Show delete vpc cni plugin"
      debug:
        msg: "{{ delete_vpc_cni.stdout }}"
    - name: "Install calico manifest"
      command: "kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico-vxlan.yaml"
      register: install_calico
    - name: "Show calico installation update output"
      debug:
        msg: "{{ install_calico.stdout }}"
    - name: "Configure Calico to disable AWS src/dst checks"
      command: "kubectl -n kube-system set env daemonset/calico-node FELIX_AWSSRCDSTCHECK=Disable"
    - name: Execute the script script to configure original aws credentials to provision infra
      shell: "sh set-original-cred.sh"
